POST https://fh-campus-rating-app-auth.auth.eu-central-1.amazoncognito.com/oauth2/token
Authorization: Basic NXExcG5oYjNpaGFmNm00ZTRoYTJsYXAzZjI6cWkydTQxbXBodmI2YnVnaG0wZXA3cWdhNW5zbzgxc2M4ZTNxODgzMnZxMWx2YXFodTdy
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###

GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles/
Authorization: Bearer eyJraWQiOiJXM3paT0pQbnF0czVDTTdCdTc0QVdBaHFcLzE4d25yMkloekplKzh4c3o2bz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1cTFwbmhiM2loYWY2bTRlNGhhMmxhcDNmMiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MjUxNjY4LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV93VjVESVBaclQiLCJleHAiOjE1OTcyNTUyNjgsImlhdCI6MTU5NzI1MTY2OCwidmVyc2lvbiI6MiwianRpIjoiNzUzYWFmY2EtMTg3Yy00MGYzLTk2OGYtOTAzN2UyYjZjYmEzIiwiY2xpZW50X2lkIjoiNXExcG5oYjNpaGFmNm00ZTRoYTJsYXAzZjIifQ.W6OhaaEAyfT-WbmSW3wxfD12v_n0HA_1tAAsBwE5n24d8wADAKjYsL4PYBK4ycXNZtbgWVVcH61p5Cw8mRaydYjZZVvRghIokCL0J8x2u386Ru5L88FvZVT4po2NKXANKV8pDCGkzEcKWyDnSyYSgANlzDY-KmDfvS6AxYIxs_fVGwSQH6z6-A6T4k27TLTLXRkj-k81dVBCK1iLxnfRf5JsGF7wpbzSBH0PHUscWEW1jIDdJsnBbKLjrfMpe617fkL_kcXKQBxtI2lMegNfld5m-e26tCTFi1b6ZsAa2COt-JSfW0CqBwyBDeS8uYZgFwKwdkXMvkLdmY6x7uLuPw

###

POST https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles
Authorization: Bearer eyJraWQiOiJXM3paT0pQbnF0czVDTTdCdTc0QVdBaHFcLzE4d25yMkloekplKzh4c3o2bz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1cTFwbmhiM2loYWY2bTRlNGhhMmxhcDNmMiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MjUxNjY4LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV93VjVESVBaclQiLCJleHAiOjE1OTcyNTUyNjgsImlhdCI6MTU5NzI1MTY2OCwidmVyc2lvbiI6MiwianRpIjoiNzUzYWFmY2EtMTg3Yy00MGYzLTk2OGYtOTAzN2UyYjZjYmEzIiwiY2xpZW50X2lkIjoiNXExcG5oYjNpaGFmNm00ZTRoYTJsYXAzZjIifQ.W6OhaaEAyfT-WbmSW3wxfD12v_n0HA_1tAAsBwE5n24d8wADAKjYsL4PYBK4ycXNZtbgWVVcH61p5Cw8mRaydYjZZVvRghIokCL0J8x2u386Ru5L88FvZVT4po2NKXANKV8pDCGkzEcKWyDnSyYSgANlzDY-KmDfvS6AxYIxs_fVGwSQH6z6-A6T4k27TLTLXRkj-k81dVBCK1iLxnfRf5JsGF7wpbzSBH0PHUscWEW1jIDdJsnBbKLjrfMpe617fkL_kcXKQBxtI2lMegNfld5m-e26tCTFi1b6ZsAa2COt-JSfW0CqBwyBDeS8uYZgFwKwdkXMvkLdmY6x7uLuPw
Content-Type: application/json

{ "article_url":"https://www.diepresse.com/5808134/musk-twittert-von-zu-hohem-kurs-tesla-aktie-fallt-um-12-prozent" }

###

POST https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles
Authorization: Bearer eyJraWQiOiJXM3paT0pQbnF0czVDTTdCdTc0QVdBaHFcLzE4d25yMkloekplKzh4c3o2bz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1cTFwbmhiM2loYWY2bTRlNGhhMmxhcDNmMiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MjUxNjY4LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV93VjVESVBaclQiLCJleHAiOjE1OTcyNTUyNjgsImlhdCI6MTU5NzI1MTY2OCwidmVyc2lvbiI6MiwianRpIjoiNzUzYWFmY2EtMTg3Yy00MGYzLTk2OGYtOTAzN2UyYjZjYmEzIiwiY2xpZW50X2lkIjoiNXExcG5oYjNpaGFmNm00ZTRoYTJsYXAzZjIifQ.W6OhaaEAyfT-WbmSW3wxfD12v_n0HA_1tAAsBwE5n24d8wADAKjYsL4PYBK4ycXNZtbgWVVcH61p5Cw8mRaydYjZZVvRghIokCL0J8x2u386Ru5L88FvZVT4po2NKXANKV8pDCGkzEcKWyDnSyYSgANlzDY-KmDfvS6AxYIxs_fVGwSQH6z6-A6T4k27TLTLXRkj-k81dVBCK1iLxnfRf5JsGF7wpbzSBH0PHUscWEW1jIDdJsnBbKLjrfMpe617fkL_kcXKQBxtI2lMegNfld5m-e26tCTFi1b6ZsAa2COt-JSfW0CqBwyBDeS8uYZgFwKwdkXMvkLdmY6x7uLuPw
Content-Type: application/json

{ "article_url":"https://www.diepresse.com/5851654/tesla-pusht-borsenkurs-mit-angekundigtem-aktiensplit" }

###

POST https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/ratings
Authorization: Bearer eyJraWQiOiJPYTAzYUFrbUF5aDY1ODVBa3IzM0FEakpSM2lWQmFVTkJKWURTaXFBbU0wPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIxaGkxcXZmOWptbTFyOXI4cXBpZzI0azU3IiwidG9rZW5fdXNlIjoiYWNjZXNzIiwic2NvcGUiOiJmaC1jYW1wdXMtcmF0aW5nLXJzXC9tYXN0ZXIiLCJhdXRoX3RpbWUiOjE1OTcyNDc0NDUsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbVwvZXUtY2VudHJhbC0xX3BsSm8yVENLUSIsImV4cCI6MTU5NzI1MTA0NSwiaWF0IjoxNTk3MjQ3NDQ1LCJ2ZXJzaW9uIjoyLCJqdGkiOiIxNjYwNTY0ZS0yYWY2LTRjYzYtOWQxYy03NTNmMDhjZmM4NWQiLCJjbGllbnRfaWQiOiIxaGkxcXZmOWptbTFyOXI4cXBpZzI0azU3In0.F1mxn5zNWhIt0UMb5INEFhO9NIsm-26BfLnuy3MDKE1Lw0bU3LmqV7QOIQ42RuUgWZkENDz4gk6bcR9L-6HTDCDx0K9Jlsls28P2cTjxpVqPq8Fe4T35XnSM80L4Lx0iXJPZIsQKuyzvP97kJ2WI5NMCJix1I3WeyW3Xol27OIINYzLxAnHBmuzjCtMoDiZ-6S7fI44ZEY6N4piRBWLj00y24i70KeBvRz-WZ-_jJZPLLye3kKjj-nIq8VQ2-f_qSeOylhpVWf7o4TnGJwcC1yOeSFfXzCgGL__BmlKxiNF1qcucou1Sj5WZRQP0JPsvqD4InODqpGtSGjNUP6nZMw
Content-Type: application/json

{
"article_id": "304b012e-29fd-4faa-b5f0-6a5dff95a989",
"rating": "6"
}

###

GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles
Authorization: Bearer eyJraWQiOiJPYTAzYUFrbUF5aDY1ODVBa3IzM0FEakpSM2lWQmFVTkJKWURTaXFBbU0wPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI3aXAwbGNiZjBjdG4xcHA2aGRlOTNycTdiMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MDY4ODM5LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9wbEpvMlRDS1EiLCJleHAiOjE1OTcwNzI0MzksImlhdCI6MTU5NzA2ODgzOSwidmVyc2lvbiI6MiwianRpIjoiNTNhMmU0ODgtMjg5NS00YWUxLThmMzktZWEyNjZjNGI1ZjVmIiwiY2xpZW50X2lkIjoiN2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjAifQ.fkYpRKy-o7Ha17yvGeRNGLKbPyfI3bwtY756vtggtDTAtxK7Gwt9hdfOU1faHbavyg29fnUQuZpDs1p6BMokjnA8GdcOJS81Zk03QdR61UzWfhUXPgy74sjrGf_6wjDIUAmtF_LRDgbKnJaBTmI4z-sNkE3SuAkTgqFZ9O_p8A3yo9BW3uEHIldIE6-BbKMQx5stfAOGx7I3uo9tR-erHv4bcjEB0sDrpyC7SE8NEJzOILnT9Nz2crS3U1J8JuV206Eo9rLsIiBnwmzKq66hhfB_dYWZDkCS-Ux_wqiBhLhXM5FXQ0af9yXwgmCV0ty_50LUVVzzVeH7hdsxsoFjzw

###

PUT https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles/a4324c8a-45ce-457d-85f2-58c65da49620
Content-Type: application/json

{
  "article_url": "https://www.diepresse.com/5808134/musk-twittert-von-zu-hohem-kurs-tesla-aktie-fallt-um-12-prozent-1337"
}

###

GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles/522b7420-5abb-4bfc-98ae-b311fd894115

###

DELETE https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles/522b7420-5abb-4bfc-98ae-b311fd894115

###

GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles

###
