POST https://fh-campus-rating-app-auth.auth.eu-central-1.amazoncognito.com/oauth2/token
Authorization: Basic N2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjA6YzJoanU0Z2pscnE4djVvYm0zaGk2OGFib3VxZHYyYWdjMXQ5ZWw4c3NjYjk1N2NjcWRu
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###

GET https://l4o4jpfyu1.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles/
Authorization: Bearer eyJzdWIiOiI3aXAwbGNiZjBjdG4xcHA2aGRlOTNycTdiMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MDY0OTg2LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9wbEpvMlRDS1EiLCJleHAiOjE1OTcwNjg1ODYsImlhdCI6MTU5NzA2NDk4NiwidmVyc2lvbiI6MiwianRpIjoiNmE5ODE3YzktODIzZC00MjBlLTgxNzEtMGFlNzIxNWM0MmVkIiwiY2xpZW50X2lkIjoiN2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjAifQ

###

POST https://l4o4jpfyu1.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles
Authorization: Bearer eyJzdWIiOiI3aXAwbGNiZjBjdG4xcHA2aGRlOTNycTdiMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MDY0OTg2LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9wbEpvMlRDS1EiLCJleHAiOjE1OTcwNjg1ODYsImlhdCI6MTU5NzA2NDk4NiwidmVyc2lvbiI6MiwianRpIjoiNmE5ODE3YzktODIzZC00MjBlLTgxNzEtMGFlNzIxNWM0MmVkIiwiY2xpZW50X2lkIjoiN2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjAifQ
Content-Type: application/json

{ "article_url":"https://www.diepresse.com/5808134/musk-twittert-von-zu-hohem-kurs-tesla-aktie-fallt-um-12-prozent" }

###

GET https://l4o4jpfyu1.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles

###

PUT https://l4o4jpfyu1.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles/a4324c8a-45ce-457d-85f2-58c65da49620
Content-Type: application/json

{
  "article_url": "https://www.diepresse.com/5808134/musk-twittert-von-zu-hohem-kurs-tesla-aktie-fallt-um-12-prozent-1337"
}

###

GET https://l4o4jpfyu1.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles/522b7420-5abb-4bfc-98ae-b311fd894115

###

DELETE https://l4o4jpfyu1.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles/522b7420-5abb-4bfc-98ae-b311fd894115

###

GET https://l4o4jpfyu1.execute-api.eu-central-1.amazonaws.com/prod/api/v1/articles

###
