GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/ratings
Authorization: Bearer eyJraWQiOiJPYTAzYUFrbUF5aDY1ODVBa3IzM0FEakpSM2lWQmFVTkJKWURTaXFBbU0wPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI3aXAwbGNiZjBjdG4xcHA2aGRlOTNycTdiMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MDg1NjQyLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9wbEpvMlRDS1EiLCJleHAiOjE1OTcwODkyNDIsImlhdCI6MTU5NzA4NTY0MiwidmVyc2lvbiI6MiwianRpIjoiNjQ5NTBkY2MtOGQzNi00ZTI0LTkwN2YtMDZiYzY3NzhmZjgyIiwiY2xpZW50X2lkIjoiN2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjAifQ.cNDnRiOmzFtvbSoFk_WzAWVu-DdSiCtV4dhdRNA5y19xIxoNdhFkpvRhG02iM0IaVF9J2nHOFkCI1SWTvqHkr56saJRxmQuLsc6QoloC-31NHItM1gZ7YJv27pwWLBjel2sNEVNqfvcrD1pE9EmECfD_7qteYg2ulvnOx06c-niFO1q9ZrJyLqR0y3LZpO3SALU3uZ2xh6RCh-Y3CpBa4YbdZp8wRtRPGyYmeX-NAGNrYPbXw5PninybxoT3m5yRSF3OfL-QALKaOokgIrXtSKSI8cvld_tT45MfcNDpAlLH6K2Jv7juN1GmZP0Pak0rfw2zaRxf3Mmpi__XTTz9tA

###

GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/accumulated/00235f21-2a53-466a-830a-9235d333d991
Authorization: Bearer eyJraWQiOiJXM3paT0pQbnF0czVDTTdCdTc0QVdBaHFcLzE4d25yMkloekplKzh4c3o2bz0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiI1cTFwbmhiM2loYWY2bTRlNGhhMmxhcDNmMiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MzMwNTM2LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV93VjVESVBaclQiLCJleHAiOjE1OTczMzQxMzYsImlhdCI6MTU5NzMzMDUzNiwidmVyc2lvbiI6MiwianRpIjoiODlmMTQ4MTItYWYzNi00MGU2LWJlY2EtZGQxZjJhMmI0MzQwIiwiY2xpZW50X2lkIjoiNXExcG5oYjNpaGFmNm00ZTRoYTJsYXAzZjIifQ.HP2JpS97Z50mKFsumPsY4VZHSixGRKd9dKHQv3SC2eQxoApY5INC_ShvS9CxPOI6LFjqH2-KeOIXM1XZAcTSgvFyJ6FwO9EtGIkTRCg6F0bu5rnonrGy3g5f5A30beNDPNRvvj7TY-yNPINcAhhdeCQ218qNK860DQNTE23huCn9tr8HNZkCOqwtvykX5tYSgBfU1vyjtYtIJv2W45TjuXAkKFppB3-Ut-3ozpJWIS7Aj95RLUmlYrcMMysydzZHeEwBopmJGxb6mKEg959-95zuJIims2NaGPT2Xok2rv0P12QmFznkhzwymWKATQHVpO7qfnn5oQe41DVC-GIpHA

###

POST https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/ratings
Authorization: Bearer eyJraWQiOiJPYTAzYUFrbUF5aDY1ODVBa3IzM0FEakpSM2lWQmFVTkJKWURTaXFBbU0wPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI3aXAwbGNiZjBjdG4xcHA2aGRlOTNycTdiMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MDg1NjQyLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9wbEpvMlRDS1EiLCJleHAiOjE1OTcwODkyNDIsImlhdCI6MTU5NzA4NTY0MiwidmVyc2lvbiI6MiwianRpIjoiNjQ5NTBkY2MtOGQzNi00ZTI0LTkwN2YtMDZiYzY3NzhmZjgyIiwiY2xpZW50X2lkIjoiN2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjAifQ.cNDnRiOmzFtvbSoFk_WzAWVu-DdSiCtV4dhdRNA5y19xIxoNdhFkpvRhG02iM0IaVF9J2nHOFkCI1SWTvqHkr56saJRxmQuLsc6QoloC-31NHItM1gZ7YJv27pwWLBjel2sNEVNqfvcrD1pE9EmECfD_7qteYg2ulvnOx06c-niFO1q9ZrJyLqR0y3LZpO3SALU3uZ2xh6RCh-Y3CpBa4YbdZp8wRtRPGyYmeX-NAGNrYPbXw5PninybxoT3m5yRSF3OfL-QALKaOokgIrXtSKSI8cvld_tT45MfcNDpAlLH6K2Jv7juN1GmZP0Pak0rfw2zaRxf3Mmpi__XTTz9tA
Content-Type: application/json

{
  "article_id": "a4324c8a-45ce-457d-85f2-58c65da49620",
  "rating": "5"
}

###

GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/ratings/257edf2c-da84-4efe-9009-ab1b5decad77/a4324c8a-45ce-457d-85f2-58c65da49620
Authorization: Bearer eyJraWQiOiJPYTAzYUFrbUF5aDY1ODVBa3IzM0FEakpSM2lWQmFVTkJKWURTaXFBbU0wPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI3aXAwbGNiZjBjdG4xcHA2aGRlOTNycTdiMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MDg1NjQyLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9wbEpvMlRDS1EiLCJleHAiOjE1OTcwODkyNDIsImlhdCI6MTU5NzA4NTY0MiwidmVyc2lvbiI6MiwianRpIjoiNjQ5NTBkY2MtOGQzNi00ZTI0LTkwN2YtMDZiYzY3NzhmZjgyIiwiY2xpZW50X2lkIjoiN2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjAifQ.cNDnRiOmzFtvbSoFk_WzAWVu-DdSiCtV4dhdRNA5y19xIxoNdhFkpvRhG02iM0IaVF9J2nHOFkCI1SWTvqHkr56saJRxmQuLsc6QoloC-31NHItM1gZ7YJv27pwWLBjel2sNEVNqfvcrD1pE9EmECfD_7qteYg2ulvnOx06c-niFO1q9ZrJyLqR0y3LZpO3SALU3uZ2xh6RCh-Y3CpBa4YbdZp8wRtRPGyYmeX-NAGNrYPbXw5PninybxoT3m5yRSF3OfL-QALKaOokgIrXtSKSI8cvld_tT45MfcNDpAlLH6K2Jv7juN1GmZP0Pak0rfw2zaRxf3Mmpi__XTTz9tA
Content-Type: application/json

###

PUT https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/ratings/33410b49-c189-420c-ad28-49ee3882b298/a4324c8a-45ce-457d-85f2-58c65da49620
Authorization: Bearer eyJraWQiOiJPYTAzYUFrbUF5aDY1ODVBa3IzM0FEakpSM2lWQmFVTkJKWURTaXFBbU0wPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI3aXAwbGNiZjBjdG4xcHA2aGRlOTNycTdiMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MDgyMDMwLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9wbEpvMlRDS1EiLCJleHAiOjE1OTcwODU2MzAsImlhdCI6MTU5NzA4MjAzMCwidmVyc2lvbiI6MiwianRpIjoiN2E5YjYxOGItODQ3ZC00ZGRlLTlkMGYtMWI0ZmQzYzg0NTViIiwiY2xpZW50X2lkIjoiN2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjAifQ.VUoaVljIIbZb_r9Zd4EmEksdORO-X3-97PyMNLIRyZ2BIe1uYgBsgajd8M1wNVrd4Hydii01gfnEaiPO_2RjZf_PrLD9i9d7d22rTfhLDtocIk6kdK3Ttn2_jAbl_fzcNJNBnJZ3I1CFWSsmiI3j-oKmmf3CsmDJgG4zBPJj6EX9K73x0sd-SFqBTj1oNly5_QJ3Iw4pnWiJy1OvDPPqeDisAu7ChpVexl_fLLBFdIuwkRrYwhtUJPY1aqDT_gDSLU5USG9zrHfFKd9gMldOgRMEB8nmFg-2A0L3kYFQ6fu5nuGweKfFRwBAaL030oBVIym6xH1PEANnrai_xALf5g
Content-Type: application/json

{
  "rating": "10"
}

###

GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/ratings/098532f7-83bd-4f95-b636-a52ffaa8952c/1

###

DELETE https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/ratings/0b5c69a2-2887-45dc-ba03-3b24bb8b7bb5/a4324c8a-45ce-457d-85f2-58c65da49620
Authorization: Bearer eyJraWQiOiJPYTAzYUFrbUF5aDY1ODVBa3IzM0FEakpSM2lWQmFVTkJKWURTaXFBbU0wPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI3aXAwbGNiZjBjdG4xcHA2aGRlOTNycTdiMCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiZmgtY2FtcHVzLXJhdGluZy1yc1wvbWFzdGVyIiwiYXV0aF90aW1lIjoxNTk3MDgyMDMwLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb21cL2V1LWNlbnRyYWwtMV9wbEpvMlRDS1EiLCJleHAiOjE1OTcwODU2MzAsImlhdCI6MTU5NzA4MjAzMCwidmVyc2lvbiI6MiwianRpIjoiN2E5YjYxOGItODQ3ZC00ZGRlLTlkMGYtMWI0ZmQzYzg0NTViIiwiY2xpZW50X2lkIjoiN2lwMGxjYmYwY3RuMXBwNmhkZTkzcnE3YjAifQ.VUoaVljIIbZb_r9Zd4EmEksdORO-X3-97PyMNLIRyZ2BIe1uYgBsgajd8M1wNVrd4Hydii01gfnEaiPO_2RjZf_PrLD9i9d7d22rTfhLDtocIk6kdK3Ttn2_jAbl_fzcNJNBnJZ3I1CFWSsmiI3j-oKmmf3CsmDJgG4zBPJj6EX9K73x0sd-SFqBTj1oNly5_QJ3Iw4pnWiJy1OvDPPqeDisAu7ChpVexl_fLLBFdIuwkRrYwhtUJPY1aqDT_gDSLU5USG9zrHfFKd9gMldOgRMEB8nmFg-2A0L3kYFQ6fu5nuGweKfFRwBAaL030oBVIym6xH1PEANnrai_xALf5g
Content-Type: application/json

###

GET https://3mq79fnen6.execute-api.eu-central-1.amazonaws.com/prod/api/v1/ratings

###
